export const schemas = {
  affiliateProduct: require('./affiliate-product.json'),
  appSetting: require('./app-setting.json'),
  appStatus: require('./app-status.json'),
  autocompleteProductTag: require('./autocomplete-product-tag.json'),
  autocompleteUniqueId: require('./autocomplete-unique-id.json'),
  catalogChallengeListItem: require('./catalog-challenge-list-item.json'),
  catalogChallenges: require('./catalog-challenges.json'),
  catalogUserSearchResult: require('./catalog-user-search-result.json'),
  catalogVideoSearchResult: require('./catalog-video-search-result.json'),
  catalogVideos: require('./catalog-videos.json'),
  challengeTranslationPayload: require('./challenge-translation-payload.json'),
  challengeTranslations: require('./challenge-translations.json'),
  challenge: require('./challenge.json'),
  devices: require('./devices.json'),
  featuredTag: require('./featured-tag.json'),
  featuredTags: require('./featured-tags.json'),
  flaggedCommentDetails: require('./flagged-comment-details.json'),
  flaggedComments: require('./flagged-comments.json'),
  followersOfUser: require('./followers-of-user.json'),
  like: require('./like.json'),
  listChallenges: require('./list-challenges.json'),
  metrics: require('./metrics.json'),
  notifications: require('./notifications.json'),
  userFollows: require('./user-follows.json'),
  userSettingsPublic: require('./user-settings-public.json'),
  user: require('./user.json'),
  users: require('./users.json'),
  version: require('./version.json'),
  videoComment: require('./video-comment.json'),
  videoComments: require('./video-comments.json'),
  videoReviewQueue: require('./video-review-queue.json'),
  video: require('./video.json'),
  videos: require('./videos.json'),
  wishlist: require('./wishlist.json'),
  
}
